### ISSUE TITLE
Integrate Sprig library for improved template writing

### ISSUE THREAD

**Issue by wtait1** [intuit/ReplayZero#4]
Go's templating engine supports calling named functions passed in via a map
https://golang.org/pkg/text/template/#FuncMap

Currently Replay Zero has its own small collection of custom functions
https://github.com/intuit/ReplayZero/blob/76137e81fec908a4076f04ba3b350ac31e4de7db/templates/funcs.go

The Sprig library specifically aims to provide many arithmetic / string / data structure-related functions out-of-the-box. The existing Replay Zero functions could even be replaced by some of these (will require template tweaks, but no code changes)
https://github.com/Masterminds/sprig

**Comment by siddhi96** [comment]
Can i try it?

**Comment by wtait1** [comment]
@siddhi96 yes go for it! Let me know if you have any extra questions
